# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         muttrcbuilder
version:      0.02
version_from: lib/Mutt/Config.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    HTML::Mason:                   0
    Module::Pluggable:             0
    XML::LibXML:                   0
    XML::LibXSLT:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
